---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: node-server-kube-svc-lb
spec:
  type: LoadBalancer
  #prevent additional hop by configuring the service to redirect external traffic only to pods running on the node that received the connection
  #externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  #- name: https
    #port: 443
    #targetPort: 8443
  selector:
    app: node-server-kube-target

# Creates a Classic LoadBalancer
# NAME                      TYPE           CLUSTER-IP       EXTERNAL-IP                           PORT(S)        AGE
# node-server-kube-svc-lb   LoadBalancer   ddd.ddd.ddd.ddd   xxx-yyy.us-west-1.elb.amazonaws.com   80:32205/TCP   16s
#
#$ curl http://xxx-yyy.us-west-1.elb.amazonaws.com
#You've hit node-server-kube-rs-7xxmf. Time=1623144811979