---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: demo
  name: node-server-kube-rc
spec:
  replicas: 1
  selector:
    app: node-server-kube-target
  template:
    metadata:
      labels:
        app: node-server-kube-target
        env: stg
    spec:
      containers:
      - name: node-server-kube
        image: xxx/node-server-kube
        livenessProbe: 
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15        
        ports:
        - containerPort: 8080