---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: node-server-kube-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  #- name: https
    #port: 443
    #targetPort: 8443
  selector:
    app: node-server-kube-target